products = [
    {"name": "Apple", "amount": 120, "price": 0.50},
    {"name": "Banana", "amount": 90, "price": 0.30},
    {"name": "Orange", "amount": 80, "price": 0.60},
    {"name": "Grapes", "amount": 50, "price": 2.50},
    {"name": "Strawberries", "amount": 40, "price": 3.00},
    {"name": "Blueberries", "amount": 35, "price": 3.20},
    {"name": "Pineapple", "amount": 25, "price": 2.80},
    {"name": "Watermelon", "amount": 15, "price": 5.00},
    {"name": "Mango", "amount": 30, "price": 1.80},
    {"name": "Papaya", "amount": 22, "price": 1.50},
    {"name": "Tomato", "amount": 100, "price": 0.90},
    {"name": "Cucumber", "amount": 85, "price": 0.70},
    {"name": "Carrot", "amount": 120, "price": 0.40},
    {"name": "Potato", "amount": 200, "price": 0.25},
    {"name": "Onion", "amount": 180, "price": 0.35},
    {"name": "Garlic", "amount": 150, "price": 0.20},
    {"name": "Spinach", "amount": 60, "price": 1.00},
    {"name": "Broccoli", "amount": 40, "price": 1.30},
    {"name": "Cabbage", "amount": 55, "price": 1.10},
    {"name": "Lettuce", "amount": 70, "price": 0.90},
    {"name": "Chicken Breast", "amount": 60, "price": 6.50},
    {"name": "Beef Steak", "amount": 40, "price": 10.00},
    {"name": "Pork Chops", "amount": 50, "price": 7.00},
    {"name": "Salmon Fillet", "amount": 30, "price": 12.00},
    {"name": "Tuna Can", "amount": 100, "price": 2.20},
    {"name": "Shrimp", "amount": 25, "price": 14.00},
    {"name": "Eggs (Dozen)", "amount": 90, "price": 3.50},
    {"name": "Milk (1L)", "amount": 100, "price": 1.20},
    {"name": "Cheddar Cheese", "amount": 40, "price": 4.50},
    {"name": "Butter", "amount": 60, "price": 3.00},
    {"name": "Yogurt", "amount": 75, "price": 1.10},
    {"name": "Bread Loaf", "amount": 80, "price": 2.00},
    {"name": "Bagels", "amount": 50, "price": 2.50},
    {"name": "Croissant", "amount": 40, "price": 2.20},
    {"name": "Pasta", "amount": 100, "price": 1.50},
    {"name": "Rice (1kg)", "amount": 120, "price": 2.00},
    {"name": "Flour (1kg)", "amount": 110, "price": 1.40},
    {"name": "Sugar (1kg)", "amount": 100, "price": 1.20},
    {"name": "Salt (1kg)", "amount": 90, "price": 0.80},
    {"name": "Olive Oil (1L)", "amount": 40, "price": 7.50},
    {"name": "Vegetable Oil (1L)", "amount": 70, "price": 4.50},
    {"name": "Ketchup", "amount": 60, "price": 2.80},
    {"name": "Mayonnaise", "amount": 55, "price": 3.20},
    {"name": "Mustard", "amount": 45, "price": 2.50},
    {"name": "Honey", "amount": 35, "price": 5.50},
    {"name": "Peanut Butter", "amount": 50, "price": 4.20},
    {"name": "Jam", "amount": 40, "price": 3.80},
    {"name": "Coffee", "amount": 70, "price": 8.00},
    {"name": "Tea", "amount": 65, "price": 4.00},
    {"name": "Cereal", "amount": 80, "price": 3.90},
    {"name": "Oats", "amount": 70, "price": 3.00},
    {"name": "Cookies", "amount": 90, "price": 2.70},
    {"name": "Chips", "amount": 100, "price": 2.20},
    {"name": "Chocolate Bar", "amount": 150, "price": 1.50},
    {"name": "Candy", "amount": 200, "price": 0.90},
    {"name": "Soda Can", "amount": 180, "price": 1.20},
    {"name": "Juice Box", "amount": 140, "price": 1.50},
    {"name": "Water Bottle (500ml)", "amount": 300, "price": 1.00},
    {"name": "Energy Drink", "amount": 60, "price": 2.80},
    {"name": "Beer (Can)", "amount": 80, "price": 2.50},
    {"name": "Wine (Bottle)", "amount": 30, "price": 15.00},
    {"name": "Toilet Paper (Pack)", "amount": 50, "price": 6.00},
    {"name": "Paper Towels", "amount": 45, "price": 4.50},
    {"name": "Soap Bar", "amount": 100, "price": 1.20},
    {"name": "Shampoo", "amount": 60, "price": 5.00},
    {"name": "Toothpaste", "amount": 70, "price": 3.00},
    {"name": "Toothbrush", "amount": 90, "price": 2.00},
    {"name": "Deodorant", "amount": 50, "price": 4.50},
    {"name": "Lotion", "amount": 45, "price": 6.00},
    {"name": "Laundry Detergent", "amount": 35, "price": 8.50},
    {"name": "Dish Soap", "amount": 55, "price": 3.20},
    {"name": "Bleach", "amount": 40, "price": 2.50},
    {"name": "Trash Bags", "amount": 70, "price": 4.00},
    {"name": "Aluminum Foil", "amount": 50, "price": 3.50},
    {"name": "Plastic Wrap", "amount": 45, "price": 3.00},
    {"name": "Tissues Box", "amount": 60, "price": 2.50},
    {"name": "Hand Sanitizer", "amount": 80, "price": 3.20},
    {"name": "Face Mask (Pack)", "amount": 40, "price": 10.00},
    {"name": "Pain Reliever", "amount": 35, "price": 5.00},
    {"name": "Vitamins", "amount": 50, "price": 8.00},
    {"name": "Cough Syrup", "amount": 25, "price": 6.50},
    {"name": "Bandages", "amount": 70, "price": 2.80},
    {"name": "Cotton Balls", "amount": 60, "price": 2.00},
    {"name": "Batteries (AA)", "amount": 90, "price": 4.00},
    {"name": "Light Bulb", "amount": 80, "price": 2.50},
    {"name": "Notebook", "amount": 100, "price": 1.80},
    {"name": "Pen", "amount": 200, "price": 0.80},
    {"name": "Pencil", "amount": 180, "price": 0.50},
    {"name": "Eraser", "amount": 150, "price": 0.40},
    {"name": "Ruler", "amount": 90, "price": 1.00},
    {"name": "Scissors", "amount": 60, "price": 2.50},
    {"name": "Glue Stick", "amount": 70, "price": 1.20},
    {"name": "Printer Paper (Ream)", "amount": 40, "price": 6.00},
    {"name": "USB Flash Drive", "amount": 30, "price": 10.00},
    {"name": "Headphones", "amount": 25, "price": 25.00},
    {"name": "Phone Charger", "amount": 35, "price": 12.00},
    {"name": "Power Bank", "amount": 20, "price": 30.00},
    {"name": "Extension Cord", "amount": 25, "price": 8.00},
    {"name": "Lamp", "amount": 15, "price": 20.00},
    {"name": "Mop", "amount": 30, "price": 10.00},
    {"name": "Broom", "amount": 40, "price": 9.00},
    {"name": "Bucket", "amount": 35, "price": 5.00},
    {"name": "Vacuum Cleaner", "amount": 10, "price": 80.00},
]
